apiVersion: thousandeyes.devnet.cisco.com/v1alpha1
kind: HTTPServerTest
metadata:
  # specify the unique test name
  name: httpserver-devnet-homepage
# specify the basic settings for the http server test
spec:
  # (required) target url for the test
  url: https://developer.cisco.com/
  # (required) frequency of ThousandEyes Cloud Agents running the test.
  # Acceptable Values: [120, 300, 600, 900, 1800, 3600] value in seconds
  interval: 1800
  #(required) array of cloud agent names
  agents:
    - agentName: Tokyo, Japan (Trial)
    - agentName: Singapore (Trial) - IPv6
  #(optional) array of alert rules. If this field is not specified, The default alert rules will be used.
  alertRules:
    - ruleName: Default HTTP Alert Rule


