# permissions for end users to edit annotationmonitorings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: annotationmonitoring-editor-role
rules:
- apiGroups:
  - devnet.cisco.com
  resources:
  - annotationmonitorings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devnet.cisco.com
  resources:
  - annotationmonitorings/status
  verbs:
  - get
