# permissions for end users to view annotationmonitorings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: annotationmonitoring-viewer-role
rules:
- apiGroups:
  - devnet.cisco.com
  resources:
  - annotationmonitorings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devnet.cisco.com
  resources:
  - annotationmonitorings/status
  verbs:
  - get
