# permissions for end users to view httpservertests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpservertest-viewer-role
rules:
- apiGroups:
  - devnet.cisco.com
  resources:
  - httpservertests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devnet.cisco.com
  resources:
  - httpservertests/status
  verbs:
  - get
