
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - devnet.cisco.com
  resources:
  - thousandeyes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devnet.cisco.com
  resources:
  - thousandeyes/finalizers
  verbs:
  - update
- apiGroups:
  - devnet.cisco.com
  resources:
  - thousandeyes/status
  verbs:
  - get
  - patch
  - update
