
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - thousandeyes.devnet.cisco.com
  resources:
  - pageloadtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - thousandeyes.devnet.cisco.com
  resources:
  - pageloadtests/finalizers
  verbs:
  - update
- apiGroups:
  - thousandeyes.devnet.cisco.com
  resources:
  - pageloadtests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - thousandeyes.devnet.cisco.com
  resources:
  - webtransactiontests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - thousandeyes.devnet.cisco.com
  resources:
  - webtransactiontests/finalizers
  verbs:
  - update
- apiGroups:
  - thousandeyes.devnet.cisco.com
  resources:
  - webtransactiontests/status
  verbs:
  - get
  - patch
  - update
