# permissions for end users to edit thousandeyestests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thousandeyestest-editor-role
rules:
- apiGroups:
  - devnet.cisco.com
  resources:
  - thousandeyestests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devnet.cisco.com
  resources:
  - thousandeyestests/status
  verbs:
  - get
