# permissions for end users to view webtransactiontests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webtransactiontest-viewer-role
rules:
- apiGroups:
  - devnet.cisco.com
  resources:
  - webtransactiontests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devnet.cisco.com
  resources:
  - webtransactiontests/status
  verbs:
  - get
