# permissions for end users to edit webtransactiontests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webtransactiontest-editor-role
rules:
- apiGroups:
  - devnet.cisco.com
  resources:
  - webtransactiontests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devnet.cisco.com
  resources:
  - webtransactiontests/status
  verbs:
  - get
