apiVersion: thousandeyes.devnet.cisco.com/v1alpha1
kind: PageLoadTest
metadata:
  name: pageloadtest-sample
spec:
  url: https://developer.cisco.com/
  interval: 600
  httpInterval: 600
  agents:
    - agentId: 4492
    - agentId: 4495

