apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # specify the unique test name
  name: ingress-pageload-sample
  annotations:
    # (required) the test type
    thousandeyes.devnet.cisco.com/test-type: page-load
    # target url for the test. If you just specify test-url, this test will be created with our default testings (interval, http interval, agents, alert rules)
    thousandeyes.devnet.cisco.com/test-url: https://developer.cisco.com/
spec:
  rules:
    - http:
        paths:
          - path: /apple
            pathType: Prefix
            backend:
              service:
                name: apple-service
                port:
                  number: 5678
          - path: /banana
            pathType: Prefix
            backend:
              service:
                name: banana-service
                port:
                  number: 5678