apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # specify the unique test name
  name: ingress-httpserver-sample
  annotations:
    # (required) the test type
    thousandeyes.devnet.cisco.com/test-type: http-server
    # specify all the basic settings of the test
    thousandeyes.devnet.cisco.com/test-spec: |
      {
        "url":"https://developer.cisco.com/",
        "interval": 600,
        "agents": [
           {"agentName":"Hong Kong (Trial)"},
           {"agentName":"Singapore (Trial) - IPv6"}
        ],
        "alertRules": [
           {"ruleName":"Default HTTP Alert Rule"}
        ]
      }
spec:
  rules:
    - http:
        paths:
          - path: /apple
            pathType: Prefix
            backend:
              service:
                name: apple-service
                port:
                  number: 5678
          - path: /banana
            pathType: Prefix
            backend:
              service:
                name: banana-service
                port:
                  number: 5678